/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BrewDetectionResult {
  found: boolean
  path?: string
  checkedPaths: Array<string>
  error?: IpcError
}

export interface BrewInfo {
  version: string
  prefix: string
  architecture: string
  path: string
}

export interface Cask {
  token: string
  name?: Array<string>
  description?: string
  installedVersion?: string
  homepage?: string
}

export declare function detectHomebrew(): BrewDetectionResult

export interface Formula {
  name: string
  fullName?: string
  description?: string
  installedVersion?: string
  homepage?: string
  dependencies?: Array<string>
  installedOnRequest?: boolean
}

export declare function getBrewInfo(): BrewInfo

export interface IpcError {
  code: string
  message: string
  raw?: string
}

export declare function listCasks(): Array<Cask>

export declare function listFormulae(): Array<Formula>

export declare function listInstalledCasks(): Array<Cask>

export declare function listInstalledFormulae(): Array<Formula>

export declare function parseCasksJson(json: string): Array<Cask>

export declare function parseFormulaeJson(json: string): Array<Formula>
