/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BrewDetectionResult {
  found: boolean
  path?: string
  checkedPaths: Array<string>
  error?: IpcError
}

export interface BrewfileEntry {
  kind: string
  name: string
  raw: string
}

export interface BrewfileExportResult {
  path?: string
  entries: Array<BrewfileEntry>
  rawContent: string
}

export interface BrewfileReadResult {
  path: string
  entries: Array<BrewfileEntry>
  rawContent: string
}

export interface BrewInfo {
  version: string
  prefix: string
  architecture: string
  path: string
}

export interface BrewPathValidationResult {
  valid: boolean
  path: string
  version?: string
  error?: IpcError
}

export interface BrewService {
  name: string
  status: string
  user?: string
  file?: string
  command?: string
}

export interface BrewUpdateResult {
  success: boolean
  stdout?: string
  stderr?: string
}

export interface Cask {
  token: string
  name?: Array<string>
  description?: string
  installedVersion?: string
  homepage?: string
}

export interface CleanupItem {
  name?: string
  path?: string
  size?: string
  kind?: string
}

export interface CleanupPreview {
  items: Array<CleanupItem>
  totalSize?: string
  rawOutput?: string
}

export interface CleanupResult {
  success: boolean
  removedItems?: number
  freedSpace?: string
  stdout?: string
  stderr?: string
}

export declare function clearCustomBrewPath(): void

export declare function detectHomebrew(): BrewDetectionResult

export interface DoctorDiagnostic {
  severity: string
  title: string
  message: string
  raw?: string
}

export interface DoctorResult {
  healthy: boolean
  diagnostics: Array<DoctorDiagnostic>
  rawOutput?: string
}

export declare function exportBrewfile(): BrewfileExportResult

export interface Formula {
  name: string
  fullName?: string
  description?: string
  installedVersion?: string
  homepage?: string
  dependencies?: Array<string>
  installedOnRequest?: boolean
}

export declare function getBrewInfo(): BrewInfo

export declare function getPackageInfo(request: PackageActionRequest): PackageInfo

export declare function installCask(token: string): PackageActionResult

export declare function installFormula(name: string): PackageActionResult

export interface IpcError {
  code: string
  message: string
  raw?: string
}

export declare function listCasks(): Array<Cask>

export declare function listFormulae(): Array<Formula>

export declare function listInstalledCasks(): Array<Cask>

export declare function listInstalledFormulae(): Array<Formula>

export declare function listOutdated(): Array<OutdatedPackage>

export declare function listServices(): Array<BrewService>

export interface OutdatedPackage {
  name: string
  kind: string
  installedVersions: Array<string>
  currentVersion?: string
  latestVersion?: string
  pinned?: boolean
  pinnedVersion?: string
}

export interface PackageActionRequest {
  name: string
  kind: string
}

export interface PackageActionResult {
  name: string
  kind: string
  success: boolean
  stdout?: string
  stderr?: string
}

export interface PackageInfo {
  name: string
  token?: string
  fullName?: string
  displayName?: Array<string>
  kind: string
  description?: string
  homepage?: string
  latestVersion?: string
  installedVersion?: string
  dependencies?: Array<string>
  caveats?: string
  installed: boolean
  rawJson?: string
}

export interface PackageSearchResult {
  name: string
  kind: string
  installed?: boolean
}

export declare function parseCasksJson(json: string): Array<Cask>

export declare function parseFormulaeJson(json: string): Array<Formula>

export declare function previewCleanup(): CleanupPreview

export declare function readBrewfile(path: string): BrewfileReadResult

export declare function restartService(request: ServiceActionRequest): ServiceActionResult

export declare function runCleanup(): CleanupResult

export declare function runDoctor(): DoctorResult

export declare function searchPackages(query: string): Array<PackageSearchResult>

export interface ServiceActionRequest {
  name: string
}

export interface ServiceActionResult {
  name: string
  action: string
  success: boolean
  stdout?: string
  stderr?: string
}

export declare function setCustomBrewPath(path: string): BrewPathValidationResult

export declare function startService(request: ServiceActionRequest): ServiceActionResult

export declare function stopService(request: ServiceActionRequest): ServiceActionResult

export declare function uninstallCask(token: string): PackageActionResult

export declare function uninstallFormula(name: string): PackageActionResult

export declare function updateHomebrewMetadata(): BrewUpdateResult

export declare function upgradeAll(): UpgradeResult

export declare function upgradePackage(request: UpgradeRequest): UpgradeResult

export interface UpgradeRequest {
  name: string
  kind: string
}

export interface UpgradeResult {
  name?: string
  kind?: string
  success: boolean
  stdout?: string
  stderr?: string
}

export declare function validateBrewPath(path: string): BrewPathValidationResult
